# Generated by Django 5.1.3 on 2024-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionbank', '0002_remove_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.CharField(choices=[('آسان', 'easy'), ('متوسط', 'normal'), ('سخت', 'hard')], max_length=11),
        ),
    ]
