# Generated by Django 5.0.6 on 2024-11-27 19:19

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('text', models.CharField(max_length=10000, null=True)),
                ('short_description', models.CharField(max_length=15000, null=True)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='my_ima0ges/')),
                ('slug', models.SlugField(default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
